DisablePathCorrection = false
EnablePathEscape = false
FireMethodNotAllowed = true
DisableBodyConsumptionOnUnmarshal = false
TimeFormat = "2006-01-02 15:04:05"
Charset = "UTF-8"

[Other]
	MyServerName = "iris"